### ISSUE TITLE
'gulp serve' error

### ISSUE THREAD

**Issue by skusunam** [amcdnl/systemjs-test#18]
Does any of you are getting this error when you run `gulp serve`?

node - 0.10.31
npm - 1.4.23

```
/Dir/angular-systemjs-seed/node_modules/gulp-less/index.js:68
    }).done(undefined, cb);
       ^
TypeError: Object #<Promise> has no method 'done'
  at DestroyableTransform._transform (/Dir/angular-systemjs-seed/node_modules/gulp-less/index.js:68:8)
  at DestroyableTransform.Transform._read (/Dir/angular-systemjs-seed/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/Dir/angular-systemjs-seed/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/Dir/angular-systemjs-seed/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/Dir/angular-systemjs-seed/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/Dir/angular-systemjs-seed/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at write (/Dir/angular-systemjs-seed/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/Dir/angular-systemjs-seed/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/Dir/angular-systemjs-seed/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at DestroyableTransform.emit (events.js:117:20)
  at emitReadable_ (/Dir/angular-systemjs-seed/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/Dir/angular-systemjs-seed/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/Dir/angular-systemjs-seed/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/Dir/angular-systemjs-seed/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/Dir/angular-systemjs-seed/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at DestroyableTransform.sourceMapInit [as _transform] (/Dir/angular-systemjs-seed/node_modules/gulp-sourcemaps/index.js:121:10)
  at DestroyableTransform.Transform._read (/Dir/angular-systemjs-seed/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
  at DestroyableTransform.Transform._write (/Dir/angular-systemjs-seed/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
  at doWrite (/Dir/angular-systemjs-seed/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
  at writeOrBuffer (/Dir/angular-systemjs-seed/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
  at DestroyableTransform.Writable.write (/Dir/angular-systemjs-seed/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
  at write (/Dir/angular-systemjs-seed/node_modules/gulp-changed/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
  at flow (/Dir/angular-systemjs-seed/node_modules/gulp-changed/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
  at DestroyableTransform.pipeOnReadable (/Dir/angular-systemjs-seed/node_modules/gulp-changed/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
  at DestroyableTransform.emit (events.js:117:20)
  at emitReadable_ (/Dir/angular-systemjs-seed/node_modules/gulp-changed/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:448:10)
  at emitReadable (/Dir/angular-systemjs-seed/node_modules/gulp-changed/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:444:5)
  at readableAddChunk (/Dir/angular-systemjs-seed/node_modules/gulp-changed/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:187:9)
  at DestroyableTransform.Readable.push (/Dir/angular-systemjs-seed/node_modules/gulp-changed/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:149:10)
  at DestroyableTransform.Transform.push (/Dir/angular-systemjs-seed/node_modules/gulp-changed/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:145:32)
  at fsOperationFailed (/Dir/angular-systemjs-seed/node_modules/gulp-changed/index.js:17:10)
  at /Dir/angular-systemjs-seed/node_modules/gulp-changed/index.js:30:8
  at Object.oncomplete (fs.js:107:15)
```

**Comment by marjan-georgiev** [comment]
Try running `npm install`. We recently upgraded gulp-less to 3.0.0

**Comment by amcdnl** [comment]
Did this resolve? @skusunam

**Comment by skusunam** [comment]
It did not last time but will try out soon and update this issue.

**Comment by marjan-georgiev** [comment]
Also, try upgrading your node, npm and jspm to latest versions.

This has been tested with npm 2.5.1, node 0.12.0, and jspm 0.13.0.

**Comment by amcdnl** [comment]
closing due to inactivity

**Comment by skusunam** [comment]
Sorry. Verified and it works fine with latest code.
