### ISSUE TITLE
gulp release is broken

### ISSUE THREAD

**Issue by lookfirst** [amcdnl/systemjs-test#19]
clear our all your bower/jspm/npm folders and then do a npm install. this shows a bunch of warnings that didn't appear before. gulp release also errors out.

```
gulp release

Error: Cannot find module 'wrappy'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/systemjs-test/angular-systemjs-seed/node_modules/gulp/node_modules/orchestrator/node_modules/end-of-stream/node_modules/once/once.js:1:76)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

Can we try to keep master stable and tested please?

**Comment by lookfirst** [comment]
I'm also seeing this... jspm install is rewriting the system.config.js to remove the `../`

```
git diff
diff --git a/system.config.js b/system.config.js
index 8fe7254..94109cc 100644
--- a/system.config.js
+++ b/system.config.js
@@ -4,8 +4,8 @@ System.config({
     "*": "*.js",
     "systemjs-test/*": "src/*.js",
     "bower_components/*": "../bower_components/*.js",
-    "github:*": "../jspm_packages/github/*.js",
-    "npm:*": "../jspm_packages/npm/*.js"
+    "github:*": "jspm_packages/github/*.js",
+    "npm:*": "jspm_packages/npm/*.js"
   },
   "buildCSS": true,
   "separateCSS": false
```

**Comment by marjan-georgiev** [comment]
Fixed the issue with the path overwrite by `jspm install`.

I could not reproduce your other problem. Tried with these verisons:

```
node version 0.10.29
npm version 2.5.1
```

**Comment by lookfirst** [comment]
must be fixed now... at least it is fixed in my project...
